baseurl: "/"
languageCode: "en-us"
theme: "hugo-xmin"
title: "Sahil Patro"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

# menu:
  # main:
    # - name: Projects
    #   url: "projects/"
    #   weight: 1
    # - name: Contact
    #   url: "contact/"
    #   weight: 2

# params:
#   description: "A website built through Hugo and blogdown."
#   footer: "&copy; [Yihui Xie](https://yihui.org) 2017 -- {Year} | [Github](https://github.com/yihui) | [Twitter](https://twitter.com/xieyihui)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
